# Generated by Django 4.2.1 on 2023-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на инструкцию'),
        ),
    ]
