# Generated by Django 4.2.1 on 2023-05-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('topic', models.CharField(choices=[('Finance', 'Finance'), ('Sales', 'Sales'), ('Marketing', 'Marketing')], max_length=255)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='instructions.instruction')),
            ],
        ),
    ]
