# Generated by Django 4.2.1 on 2023-05-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCs', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(choices=[('Исполнительный директор', 'Исполнительный директор'), ('Главный бухгалтер', 'Главный бухгалтер'), ('Генеральный директор', 'Генеральный директор')], max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
